spring:

  datasource:
    url: jdbc:h2:~/Study/h2/test;mode=mysql
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #default_batch_fetch_size: 100
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
